name: CI/CD Pipeline - Facturacion IConstruye

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Setup Yarn
        run: corepack enable && corepack prepare yarn@3.6.1 --activate

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Run tests with coverage
        run: yarn test --coverage

  synth:
    name: CDK Synth
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Setup Yarn
        run: corepack enable && corepack prepare yarn@3.6.1 --activate

      - name: Install dependencies
        run: yarn install
        working-directory: facturacion-iconstruye/infra

      - name: Build CDK
        run: yarn build
        working-directory: facturacion-iconstruye/infra

      - name: CDK Synth
        run: npx cdk synth
        working-directory: facturacion-iconstruye/infra

  deploy:
    name: CDK Deploy
    runs-on: ubuntu-latest
    needs: synth

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Setup Yarn
        run: corepack enable && corepack prepare yarn@3.6.1 --activate

      - name: Install dependencies
        run: yarn install
        working-directory: facturacion-iconstruye/infra

      - name: Build CDK
        run: yarn build
        working-directory: facturacion-iconstruye/infra

      - name: CDK Deploy
        run: npx cdk deploy --require-approval never
        working-directory: facturacion-iconstruye/infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
